---
- hosts: all
  serial: 1
  vars:
  - debug: false
  - packages: [git, lighttpd]
  tasks:
  - block:
    - name: install packages
      package:
        name: "{{item}}"
        state: installed
      with_items:
        - "{{packages}}"
      register: packages_state
    - debug:
        msg: "{{packages_state}}"
      when: "debug == true"
    - name: copy lighttpd config file
      template:
        src: "lighttpd.conf.j2"
        dest: "/etc/lighttpd/conf-enabled/00-test.conf"
    - name: restart lighttpd
      service:
        name: lighttpd
        state: restarted
    rescue:
    - name: remove lighttp config file
      file:
        dest: "/etc/lighttpd/conf-enabled/00-test.conf"
        state: absent
    - name: remove installed packages
      package:
        name: "{{item}}"
        state: absent
        purge: true
      with_items:
        - "{{packages}}"
      when: "packages_state['changed'] == true"
    - fail:
