---
- hosts: all
  tasks:
  - include_vars: "includes/{{ ansible_os_family }}.yml"

  - debug:
      msg: "going to remove package {{apache}}"

  # This uses a variable as this changes per distribution.
  - name: "remove the apache package"
    action: "package name={{apache}} state=absent"
