---
- hosts: all
  strategy: free
#   strategy: linear
#  serial: 1
  tasks:
  - debug:
      msg: "{{ ansible_local['times']['general'] }}"
  - shell:
      cmd: "sleep {{ ansible_local['times']['general']['t1'] }}"
  - shell:
      cmd: "sleep {{ ansible_local['times']['general']['t2'] }}"
